version: '2'
services: 
    db:
        build: .
        container_name: mysql_test
        environment: 
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: testdb
        ports: 
            - "3306:3306"